description: Fix oddly formatted section range
tags: structural
status: approved
issue_number: 2026-02-04
fr_doc: 89FR7523
reference: https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/117162136/comments

patches:
  '001':
    first_issue_date: '2026-02-04'
    last_issue_date: '2026-03-31'
